# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a39f39a82a2dc7412c853b0be309109a20ea4855eb870f95685ec058273ab1f7de3b7da10143fc306a8848c2e1b03585767536693324144aa9073902c10ba2eb

test:
  secret_key_base: ccf1c3dd9ae909939565e6ba0ea7895e08f4c2cd5cadf2ed4684f8c7e992d437c8c87df010f971b4c07b23936f391d0e589ecf3ba2b3325bc658a9f8d75f7cb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
